version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bookland_user
      - POSTGRES_PASSWORD=bookland_password
      - POSTGRES_DB=bookland
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: 