# Generated by Django 5.1.6 on 2025-02-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftranslate', '0002_pdfdocument_translation_status_wordentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='total_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='translated_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='translation_progress',
            field=models.IntegerField(default=0),
        ),
    ]
