# Generated by Django 5.1.6 on 2025-02-22 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftranslate', '0004_pdfdocument_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reviewed', models.DateTimeField(blank=True, help_text='When this card was last reviewed', null=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, help_text='When this card should be reviewed next')),
                ('review_count', models.IntegerField(default=0, help_text='Number of times this card has been reviewed')),
                ('interval', models.FloatField(default=1.0, help_text='Current interval in days between reviews')),
                ('ease_factor', models.FloatField(default=2.5, help_text='SuperMemo 2 ease factor, minimum 1.3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
                ('word_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard', to='pdftranslate.wordentry')),
            ],
            options={
                'ordering': ['next_review'],
                'indexes': [models.Index(fields=['user', 'next_review'], name='pdftranslat_user_id_e3625e_idx'), models.Index(fields=['word_entry'], name='pdftranslat_word_en_9ad2f0_idx')],
            },
        ),
    ]
