# Generated by Django 5.1.6 on 2025-03-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftranslate', '0005_flashcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='ease_factor',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='interval',
            field=models.CharField(choices=[('again', '<10m'), ('hard', '<15m'), ('good', '1d'), ('easy', '2d')], default='good', help_text='Current review interval', max_length=10),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='review_count',
            field=models.IntegerField(default=0, help_text='Number of successful reviews'),
        ),
    ]
