# Generated by Django 5.1.6 on 2025-04-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftranslate', '0006_remove_flashcard_ease_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='target_language',
            field=models.CharField(choices=[('ru', 'Russian'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('pl', 'Polish'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], default='ru', max_length=5),
        ),
    ]
