# Generated by Django 5.1.6 on 2025-03-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftranslate', '0006_remove_flashcard_ease_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordentry',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordentry',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
