# Generated by Django 5.1.6 on 2025-03-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftranslate', '0002_userprofile'),
        ('pdftranslate', '0007_wordentry_context_alter_wordentry_position'),
    ]

    operations = [
    ]
