# Generated by Django 5.1.6 on 2025-03-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftranslate', '0003_add_profile_fields'),
        ('pdftranslate', '0008_merge_20250313_0935'),
    ]

    operations = [
    ]
